
SafeAddString(SI_LLS_ITEM_SUMMARY, "Item Summary", 1)
SafeAddString(SI_LLS_ITEM_SUMMARY_TOOLTIP, "<<1>> will print a summary of items when done.", 1)
SafeAddString(SI_LLS_LOOT_SUMMARY, "Loot History Summary", 1)
SafeAddString(SI_LLS_LOOT_SUMMARY_TOOLTIP, "<<1>> will print a summary of loot when done.", 1)
SafeAddString(SI_LLS_MIN_ITEM_QUALITY, "Minimum Item Quality", 1)
SafeAddString(SI_LLS_MIN_ITEM_QUALITY_TOOLTIP, "Filter out any items with a quality less than this minimum quality from appearing in the summary.", 1)
SafeAddString(SI_LLS_MIN_LOOT_QUALITY, "Minimum Loot Quality", 1)
SafeAddString(SI_LLS_MIN_LOOT_QUALITY_TOOLTIP, "Filter out any loot with a quality less than this minimum quality from appearing in the summary.", 1)
SafeAddString(SI_LLS_SHOW_ITEM_ICONS, "Show Item Icons", 1)
SafeAddString(SI_LLS_SHOW_ITEM_ICONS_TOOLTIP, "Display icons to the left of item names that appear in the summary.", 1)
SafeAddString(SI_LLS_ICON_SIZE, "Icon Size", 1)
SafeAddString(SI_LLS_ICON_SIZE_TOOLTIP, "Set icon size in percent.", 1)
SafeAddString(SI_LLS_SHOW_LOOT_ICONS, "Show Loot Icons", 1)
SafeAddString(SI_LLS_SHOW_LOOT_ICONS_TOOLTIP, "Display icons to the left of loot names that appear in the summary.", 1)
SafeAddString(SI_LLS_SHOW_ITEM_TRAITS, "Show Item Trait Names", 1)
SafeAddString(SI_LLS_SHOW_ITEM_TRAITS_TOOLTIP, "Display trait names in parenthesis to the right of item names that appear in the summary.", 1)
SafeAddString(SI_LLS_SHOW_LOOT_TRAITS, "Show Loot Trait Names", 1)
SafeAddString(SI_LLS_SHOW_LOOT_TRAITS_TOOLTIP, "Display trait names in parenthesis to the right of loot names that appear in the summary.", 1)
SafeAddString(SI_LLS_HIDE_ITEM_SINGLE_QTY, "Hide Quantity for Single Items", 1)
SafeAddString(SI_LLS_HIDE_ITEM_SINGLE_QTY_TOOLTIP, "Quantities will only be printed to the right of item names that have a quantity greater than one.", 1)
SafeAddString(SI_LLS_HIDE_LOOT_SINGLE_QTY, "Hide Quantity for Single Items", 1)
SafeAddString(SI_LLS_HIDE_LOOT_SINGLE_QTY_TOOLTIP, "Quantities will only be printed to the right of loot names that have a quantity greater than one.", 1)
SafeAddString(SI_LLS_COMBINE_DUPLICATES, "Combine Repeated Items", 1)
SafeAddString(SI_LLS_COMBINE_DUPLICATES_TOOLTIP, "Links that appear more than once in the summary are combined into a single link and their quantities are summed together.", 1)
SafeAddString(SI_LLS_SHOW_ITEM_NOT_COLLECTED, "<<1>> Show Uncollected Sets Icons", 1)
SafeAddString(SI_LLS_SHOW_ITEM_NOT_COLLECTED_TOOLTIP, "Display icons to the right of item names if their set pieces are not collected.", 1)
SafeAddString(SI_LLS_SHOW_LOOT_NOT_COLLECTED, "<<1>> Show Uncollected Sets Icons", 1)
SafeAddString(SI_LLS_SHOW_LOOT_NOT_COLLECTED_TOOLTIP, "Display icons to the right of loot names if their set pieces are not collected.", 1)
SafeAddString(SI_LLS_SORT_ORDER_TOOLTIP, "Choose how the summary will be sorted", 1)
SafeAddString(SI_LLS_DELIMITER, "List Delimiter", 1)
SafeAddString(SI_LLS_DELIMITER_TOOLTIP, "Choose which characters will separate summary entries. \"\\n\" signifies that all list entries appear on separate lines.", 1)
SafeAddString(SI_LLS_LINK_STYLE, "Link Style", 1)
SafeAddString(SI_LLS_LINK_STYLE_TOOLTIP, "Choose how links will appear.", 1)
SafeAddString(SI_LLS_QUOTES, "\"<<X:1>>\"", 1)
SafeAddString(SI_LLS_SHOW_COUNTER, "<<1>> Count", 1)
SafeAddString(SI_LLS_SHOW_COUNTER_TOOLTIP, "Displays a count of <<1>> at the end of the summary.", 1)
SafeAddString(SI_LLS_COUNTER_FORMAT_SINGLE, "(<<1>> <<2>>)", 1)
SafeAddString(SI_LLS_COUNTER_FORMAT_PLURAL, "(<<1*2>>)", 1)
SafeAddString(SI_LLS_PLURAL, "<<1*2>>", 1)